### ISSUE TITLE
Having a dockerfile or clearer install instructions

### ISSUE THREAD

**Issue by Kiblyn11** [returntocorp/pfff#114]
Would it be possible to have a dockerfile or clearer install instructions ?
I tried to install it in a docker but it fails mysteriously, I did try to follow the vague install instructions.

Here is my dockerfile
```
FROM ubuntu:18.04
RUN apt update && apt install -y ocaml opam menhir swi-prolog default-jre libncurses5-dev libncursesw5-dev binutils-gold
COPY . /pfff
RUN opam init -a && eval $(opam env)
RUN cd /pfff && ./configure && make depend && make && make opt
ENTRYPOINT [ "/usr/local/bin/codegraph" ]
```

I get this error at make depend:
```
File "parser_ml.mly", line 100, characters 9-10:
Error: unexpected character(s).
Makefile:58: recipe for target 'parser_ml.ml' failed
make[1]: Leaving directory '/pfff/lang_ml/parsing'
make[1]: *** [parser_ml.ml] Error 1
make: *** [depend] Error 2
```

**Comment by Kiblyn11** [comment]
Or I thought about taking the semgrep docker image but I'm afraid there is only sgrep available there ?

**Comment by mjambon** [comment]
Hello! I added a simple Dockerfile, which uses a base image with opam pre-installed. This is the option I'd recommend for building pfff.

If you really need to start from a vanilla ubuntu image, you can install opam from a deb package from a 3rd-party repository. See the instructions in `.github/workflows/test.yml`. You may need to install a C compiler and various build tools as well.
