### ISSUE TITLE
Ask Github to delist this repository as a fork?

### ISSUE THREAD

**Issue by teymour-aldridge** [returntocorp/pfff#226]
Given that this fork is a superset of the commits on the repository it is forked from, it might be worth asking Github to delist it as a fork.
I found it a bit confusing at first (though I figured out based on the README.md of the repository this repository is forked from that this is the correct repository).
Github has a note about this in their documentation https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork
This is just a suggestion :)
This project looks awesome by the way – I'm itching to try it out.

**Comment by aryx** [comment]
Good idea! I've just created a ticket with github contact support. Let's see!

**Comment by teymour-aldridge** [comment]
Hopefully it will work. In any case, it’s not a really major problem.

In any case, this looks like an interesting project (a bit like LGTM.com <http://lgtm.com/> which Github recently acquired but easier to use and open source).
