### ISSUE TITLE
Move 'semgrep.yml' configuration to cloud app

### ISSUE THREAD

**Issue by mschwager** [returntocorp/pfff#258]
As part of https://github.com/returntocorp/enterprise/issues/298 and internally dogfooding the cloud service, lets move the local Semgrep configuration and manage it there. This will allow us to centrally and consistently manage our Semgrep configurations.

**Comment by ackalker** [comment]
Does this mean the configuration will no longer be available to people who don't use the cloud service?
Also: the link to the referenced issue results in a 404, presumably because it references a private repository. I don't think it is of much use to people who don't have access.

**Comment by aryx** [comment]
I've moved some of the generic ocaml rules in sengrep.yml to semgrep-rules/; the remaining ones are really semgrep specific and I think it's fine to keep this local semgrep.yml file and have it used in circleCI, that we also dogfood using circleCI.
We can also have another CI check using the cloud service; we can have both.
