### ISSUE TITLE
Add using/with to AST_generic.ml

### ISSUE THREAD

**Issue by Sjord** [returntocorp/pfff#342]
Several languages have syntax to declare a variable and automatically dispose of it at the end of the block.

[Python's `with`](https://www.python.org/dev/peps/pep-0343/):

```python
with opened(filename, "w") as f:
    with stdout_redirected(f):
        print "Hello world"
```

[C# has `using`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement):

```csharp
using (var reader = new StringReader(manyLines))
{
    string? item;
    do {
        item = reader.ReadLine();
        Console.WriteLine(item);
    } while(item != null);
}
```

`using` [takes an expression or a variable declaration](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#the-using-statement). A variable declaration can consist of multiple declarations in one:

```csharp
using (Font font3 = new Font("Arial", 10.0f), font4 = new Font("Arial", 10.0f))
{
   // Use font3 and font4.
}
```

I would propose the following:

```ocaml
stmt =
| WithUsingResource of tok * stmt * stmt 
```

Where:

* `tok` is the `using` or `with`.
* First `stmt` is the resource to be disposed at the end. So this is typically an ExprStmt or a DefStmt. 
* Second `stmt` is a `Block` with the code.

Should we use something more specific than `stmt` for the resource acquisition part? Is the name WithUsingResource OK?

This replaces `OSWS_With`. Should we remove that immediately, or keep it around for backward compatibility?

**Comment by aryx** [comment]
Yes you can remove the osow_with construct once we have UsingWithResource
