### ISSUE TITLE
Metavariable syntax for python

### ISSUE THREAD

**Issue by mjambon** [returntocorp/pfff#364]
The python lexer accepts [identifiers like `$foo`](https://github.com/returntocorp/pfff/blob/7d929741bb945e38df94c2adca2481ef7589b912/lang_python/parsing/Lexer_python.mll#L435) but they're not valid metavariables according to [Metavars_generic.ml in semgrep](https://github.com/returntocorp/semgrep/blob/1d19da8d357fce01b9ae2827bb1ee0ef19684963/semgrep-core/core/Metavars_generic.ml#L122-L123).

Is this a bug? If so, we can make it fail with a helpful error message like "semgrep metavariables may no longer be lowercase since semgrep vx.x.x".

**Comment by mjambon** [comment]
@nbrahms points out that patterns containing `$foo` don't parse: https://semgrep.dev/s/3xZG/

The metavariable syntax is checked by semgrep-core/parsing/Check_semgrep.ml (check_pattern_metavars), resulting in a runtime error as desired. Does the lexer accept lowercase `$foo` on purpose?

**Comment by aryx** [comment]
Not on purpose; I was lazy to introduce a new regexp for uppercase identifiers and also I preferred to have only
one place specifying the syntax of a metavariable as we can change that sometimes, so simpler to be more general in the Python lexer and catch the error later in Check_semgrep.ml.

**Comment by aryx** [comment]
I can fix Lexer_python.mll if it bothers you. I think right now the syntax for metavariable is pretty fixed.
