### ISSUE TITLE
Source cloning on Windows fails due to the use of a reserved name on Windows in the filename

### ISSUE THREAD

**Issue by smorimoto** [returntocorp/pfff#395]
The "aux""is a reserved name in Windows and cannot be used in filenames. I don't think there is a big problem at this moment, but it should be changed: `data/js_stdlib/aux.js` -> `data/js_stdlib/???.js`

```
Error: error: invalid path 'data/js_stdlib/aux.js'
Error: The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 128
```

**Comment by aryx** [comment]
sure
