### ISSUE TITLE
Error: Unbound module Graph

### ISSUE THREAD

**Issue by GabrieleMaurina** [returntocorp/pfff#63]
Im on Ubuntu 18.04, I ran ./configure and make depend without any issues but when I run make I get this error:

`
Error: Unbound module Graph
../../Makefile.common:160: recipe for target 'graphe.cmo' failed
make[2]: *** [graphe.cmo] Error 2
make[2]: Leaving directory '/home/gabriele/Documents/workspace/git/pfff/commons_wrappers/graph'
Makefile:232: recipe for target 'rec' failed
make[1]: *** [rec] Error 1
make[1]: Leaving directory '/home/gabriele/Documents/workspace/git/pfff'
Makefile:223: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by aryx** [comment]
did you install ocamlgraph?

Anyway, the simplest way to install pfff is to install via OPAM the OCaml Package Manager.
Did you manage to get 'opam install pfff' working?

**Comment by GabrieleMaurina** [comment]
Thank you very much for your quick response.
I must admit I'm not familiar with ocaml and I did not install ocamlgraph,
since it was not listed in the packages to be installed in the
install_linux.txt file. I will try, thank you very much.

Will installing via OPAM take care of all the dependencies? If so, that is
awesome.

Gabriel

**Comment by GabrieleMaurina** [comment]
Here is an update:

if I run opan install pfff, i get this error:

The following actions will be performed:
  ∗ install ocamlfind  1.8.1             [required by pfff]
  ∗ install ocamlbuild 0.14.0            [required by ocamlnet]
  ∗ install ocamlgraph 1.8.8             [required by pfff]
  ∗ install num        1.3               [required by pfff]
  ∗ install base-bytes base              [required by ocamlnet]
  ∗ install ocamlnet   4.1.7             [required by json-wheel]
  ∗ install json-wheel 1.0.6+safe-string [required by pfff]
  ∗ install pfff       0.39.5
===== ∗ 8 =====
Do you want to continue? [Y/n] y

<><> Gathering sources
><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[json-wheel.1.0.6+safe-string] found in cache
[num.1.3] found in cache
[ocamlbuild.0.14.0] found in cache
[ocamlfind.1.8.1] found in cache
[ocamlgraph.1.8.8] found in cache
[ocamlnet.4.1.7] found in cache
[pfff.0.39.5] found in cache

<><> Processing actions
<><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of ocamlbuild failed at
"/s/chopin/a/grad/gmaurina/.opam/opam-init/hooks/sandbox.sh build make
check-if-preinstalled all opam-install".
[ERROR] The compilation of ocamlfind failed at
"/s/chopin/a/grad/gmaurina/.opam/opam-init/hooks/sandbox.sh build make opt".

#=== ERROR while compiling ocamlfind.1.8.1
====================================#
# context     2.0.1 | linux/x86_64 | ocaml-system.4.07.0 |
https://opam.ocaml.org#e7a02ec1
# path        ~/.opam/default/.opam-switch/build/ocamlfind.1.8.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build make opt
# exit-code   2
# env-file    ~/.opam/log/ocamlfind-2716-e0ba4f.env
# output-file ~/.opam/log/ocamlfind-2716-e0ba4f.out
### output ###
# [...]
# ocamlopt -I +compiler-libs -g -opaque -c fl_lint.ml
# ocamlopt -I +compiler-libs -g -a -o findlib.cmxa findlib_config.cmx
fl_split.cmx fl_metatoken.cmx fl_meta.cmx fl_metascanner.cmx fl_topo.cmx
fl_package_base.cmx findlib.cmx fl_args.cmx fl_lint.cmx
# if [ 1 -gt 0 ]; then \
#     ocamlopt -I +compiler-libs -g -shared -o findlib.cmxs
findlib_config.cmx fl_split.cmx fl_metatoken.cmx fl_meta.cmx
fl_metascanner.cmx fl_topo.cmx fl_package_base.cmx findlib.cmx fl_args.cmx
fl_lint.cmx; \
# fi
# gcc: fatal error: ‘-fuse-linker-plugin’, but liblto_plugin.so not found
# compilation terminated.
# File "caml_startup", line 1:
# Error: Error during linking
# make[1]: *** [Makefile:68: findlib.cmxa] Error 2
# make[1]: Leaving directory
'/s/chopin/a/grad/gmaurina/.opam/default/.opam-switch/build/ocamlfind.1.8.1/src/findlib'
# make: *** [Makefile:17: opt] Error 2

#=== ERROR while compiling ocamlbuild.0.14.0
==================================#
# context     2.0.1 | linux/x86_64 | ocaml-system.4.07.0 |
https://opam.ocaml.org#e7a02ec1
# path        ~/.opam/default/.opam-switch/build/ocamlbuild.0.14.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build make
check-if-preinstalled all opam-install
# exit-code   2
# env-file    ~/.opam/log/ocamlbuild-2716-9088e2.env
# output-file ~/.opam/log/ocamlbuild-2716-9088e2.out
### output ###
# if test -d /usr/lib64/ocaml/ocamlbuild; then\
#   >&2 echo "ERROR: Preinstalled ocamlbuild detected at"\
#        "/usr/lib64/ocaml/ocamlbuild";\
#   >&2 echo "Installation aborted; if you want to bypass this"\
#         "safety check, pass CHECK_IF_PREINSTALLED=false to make";\
#   exit 2;\
# fi
# ERROR: Preinstalled ocamlbuild detected at /usr/lib64/ocaml/ocamlbuild
# Installation aborted; if you want to bypass this safety check, pass
CHECK_IF_PREINSTALLED=false to make
# make: *** [Makefile:410: check-if-preinstalled] Error 2

<><> Error report
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocamlbuild 0.14.0
│ λ build ocamlfind  1.8.1
└─
╶─ No changes have been performed

Any ideas?

Gabriele

**Comment by aryx** [comment]
Seems like a bug in ocamlbuild then, but I'm surprised because many people
have installed this package.
Do you have a special configuration? Do you use a special environment that
could cause those issues?
Try 'opam update; opam upgrade; opam install pfff;

**Comment by GabrieleMaurina** [comment]
Hi Yoann,
I was working on the university machine, which runs Fedora 30 server.

Anyway now I am trying on my personal machine, for which I have super user
privileges. It is  runs Ubuntu 18.04. I executed the following commands:

   - opam update
   - opam upgrade
   - opam install pfff

But I got the error:
[ERROR] pfff is not available because your system doesn't comply with
ocaml-version >= "4.01.0" & ocaml-version < "4.03.0".

Indeed I have ocaml 4.05.0. But pfff page
https://opam.ocaml.org/packages/pfff/pfff.0.39.5/ says ocaml should be
between 05 and 09. What should I do?

Thank you so much,
Gabriele

**Comment by GabrieleMaurina** [comment]
Update:

running sudo opam show pfff produces this results, which shows that pfff
0.39.5 isn't available:

[WARNING] Running as root is not recommended
             package: pfff
             version: 0.29
          repository: default
        upstream-url: https://github.com/facebook/pfff/archive/v0.29.tar.gz
       upstream-kind: http
   upstream-checksum: b5be003671e6667dcb121104bc92fb72
            homepage: https://github.com/facebook/pfff/wiki/Main
         bug-reports: https://github.com/facebook/pfff/issues
            dev-repo: https://github.com/facebook/pfff.git
              author: Yoann Padioleau <pad@fb.com>
             depends: ocamlfind & camlp4 & num
   installed-version:
  available-versions: 0.25.1, 0.27.1, 0.27.3, 0.29
         description: Tools and APIs for program analysis, code
visualization, refactoring

pfff is a set of tools and APIs to perform some static analysis,
dynamic analysis, code visualizations, code navigations, or
style-preserving source-to-source transformations such as refactorings
on source code. For now the effort is focused on PHP but there is also
good support for C, C++, Java, HTML, Javascript, Css, and preliminary
support for Erlang, Python, C#, Lisp, Scheme, Haskell, OPA, Sql, and
even TeX. There is also very good support for OCaml and noweb
(literate programming) so that pfff can be used on the code of pfff
itself.

For more information see https://github.com/facebook/pfff/wiki/Main

**Comment by GabrieleMaurina** [comment]
Upgrading opam worked for me and I was able to install pfff.

One more question now: if I wanna use it from command line, how can I do it
now?

**Comment by aryx** [comment]
The command 'pfff' gives access to the different parsers. Try ~/pfff/pfff -parse_js /path/to/js/project
or ~/pfff/pfff -dump_js /path/to/foo.js to dump the AST of foo.js.
There is no much documentation so if you're not familiar with OCaml, you will have a hard time.
Otherwise look at the .mli and the different main_xxx.ml files to get a sense of the feature set.

**Comment by GabrieleMaurina** [comment]
But I don't have a ~/pfff folder. Should I?

**Comment by aryx** [comment]
by ~/pfff I meant where you decompressed and compiled pfff.
If you install pfff via OPAM then you'll get only the API in pfff (a set of OCaml modules you can use in your own OCaml programs). If you want to run the few  command-line tools in pfff you need to compile pfff from source.

**Comment by GabrieleMaurina** [comment]
Ok, if I compile now on my Ubuntu 18.04 machine I get this:

File "/home/gabriele/Documents/workspace/git/pfff/lang_js/parsing/
meta_cst_js.ml", line 1:
Error: Could not find the .cmi file for interface

 /home/gabriele/Documents/workspace/git/pfff/lang_js/parsing/meta_cst_js.mli.
make[2]: *** [meta_cst_js.cmo] Error 2
make[1]: *** [rec] Error 1
make: *** [all] Error 2

What is it? Should I open and issue?

Gabriele

**Comment by aryx** [comment]
you need make depend first. then make

**Comment by GabrieleMaurina** [comment]
Thank you so much for putting up with me.
I did make depend first, but now that you mentioned I double checked and it
is giving me some error in between a lot of warnings.

Here is the output of make depend:

ocamldep -pp "cpp -Wno-invalid-pp-token" -I commons -I commons_ocollection
-I commons_core -I commons_wrappers/graph -I globals -I h_visualization -I
h_files-format -I h_program-lang -I graph_code -I lang_ml/parsing -I
lang_ml/analyze -I lang_skip/parsing -I lang_skip/analyze -I
lang_nw/parsing -I lang_nw/analyze -I lang_lisp/parsing -I
lang_lisp/analyze -I lang_haskell/parsing -I lang_haskell/analyze -I
lang_php/parsing -I lang_php/pretty -I lang_sql/parsing -I lang_js/parsing
-I lang_js/analyze -I lang_cpp/parsing -I lang_cpp/analyze -I
lang_c/parsing -I lang_c/analyze -I lang_java/parsing -I lang_java/analyze
-I lang_python/parsing -I lang_python/analyze -I lang_go/parsing -I
lang_go/analyze -I lang_csharp/parsing -I lang_csharp/analyze -I
lang_rust/parsing -I lang_rust/analyze -I lang_erlang/parsing -I
lang_erlang/analyze -I lang_php/analyze -I lang_php/analyze/foundation -I
lang_php/analyze/checker -I lang_php/analyze/tools -I
lang_php/analyze/qa_test -I lang_html/parsing -I lang_html/analyze -I
lang_css/parsing -I lang_web/parsing -I lang_text -I lang_GENERIC/parsing
-I lang_GENERIC/analyze -I lang_FUZZY/parsing -I metagen -I demos -I
commons_wrappers/graph *.mli *.ml > .depend
main_codequery.ml:83:208: warning: missing terminating ' character
 no -Dpa.filternull=yes -Dpa.unknowntypes=no net.sf.bddbddb.Solver %s' %
(java_cmd, cla
                                                                     ^
main_codequery.ml:143:9: warning: missing terminating ' character
   (* don't care about the remaining prolog stuff so exit earlier *)
         ^
cc1: warning: unrecognized command line option ‘-Wno-invalid-pp-token’
main_codeslicer.ml:19:12: warning: missing terminating ' character
  * Once you've seen one driver you got the main ideas and seeing
            ^
main_codeslicer.ml:23:22: warning: missing terminating ' character
  * architecture as it's difficult to find a meaningful layering of the code
                      ^
main_codeslicer.ml:41:21: warning: missing terminating ' character
  * is far smaller it's also faster to run expensive analysis that are
                     ^
main_codeslicer.ml:143:43: warning: missing terminating ' character
      * but that should not anymore, so let's reconsider all children!
                                           ^
cc1: warning: unrecognized command line option ‘-Wno-invalid-pp-token’
set -e; for i in commons commons_ocollection commons_core
commons_wrappers/graph  globals h_visualization h_files-format
h_program-lang graph_code lang_ml/parsing lang_ml/analyze lang_skip/parsing
lang_skip/analyze lang_nw/parsing lang_nw/analyze lang_lisp/parsing
lang_lisp/analyze lang_haskell/parsing lang_haskell/analyze
lang_php/parsing lang_php/pretty lang_sql/parsing lang_js/parsing
lang_js/analyze lang_cpp/parsing lang_cpp/analyze lang_c/parsing
lang_c/analyze lang_java/parsing lang_java/analyze lang_python/parsing
lang_python/analyze lang_go/parsing lang_go/analyze lang_csharp/parsing
lang_csharp/analyze lang_rust/parsing lang_rust/analyze lang_erlang/parsing
lang_erlang/analyze lang_php/analyze lang_php/analyze/foundation
lang_php/analyze/checker lang_php/analyze/tools lang_php/analyze/qa_test
lang_html/parsing lang_html/analyze lang_css/parsing lang_web/parsing
lang_text lang_GENERIC/parsing lang_GENERIC/analyze lang_FUZZY/parsing
metagen demos; do echo $i; make -C $i depend; done
commons
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/commons'
ocamldep.opt  *.mli *.ml  > .depend
for i in ; do ocamldep.opt $i/*.ml $i/*.mli >> .depend; done
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/commons'
commons_ocollection
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/commons_ocollection'
ocamldep.opt -I ../commons *.mli *.ml  > .depend
for i in ; do ocamldep.opt $i/*.ml $i/*.mli >> .depend; done
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/commons_ocollection'
commons_core
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/commons_core'
ocamldep.opt -I ../commons *.mli *.ml  > .depend
for i in ; do ocamldep.opt $i/*.ml $i/*.mli >> .depend; done
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/commons_core'
commons_wrappers/graph
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/commons_wrappers/graph'
ocamldep  -I ../../commons *.mli *.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/commons_wrappers/graph'
globals
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/globals'
ocamldep  -I ../commons *.mli *.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/globals'
h_visualization
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/h_visualization'
ocamldep  -I ../commons *.mli *.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/h_visualization'
h_files-format
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/h_files-format'
ocamldep  -I ../commons *.mli *.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/h_files-format'
h_program-lang
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/h_program-lang'
ocamldep  -I ../commons -I ../h_files-format *.mli *.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/h_program-lang'
graph_code
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/graph_code'
ocamldep  -I ../commons -I ../commons_core -I ../commons_wrappers/graph -I
../h_program-lang *.mli *.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/graph_code'
lang_ml/parsing
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/lang_ml/parsing'
ocamldep  -I ../../commons -I ../../commons_core -I ../../globals -I
../../h_program-lang *.mli *.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/lang_ml/parsing'
lang_ml/analyze
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/lang_ml/analyze'
ocamldep  -I ../../commons -I ../../commons_ocollection -I
../../commons_core -I ../../globals -I ../../h_program-lang -I
../../graph_code -I ../../h_visualization -I ../../globals -I ../parsing
*.mli *.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/lang_ml/analyze'
lang_skip/parsing
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/lang_skip/parsing'
ocamldep  -I ../../commons -I ../../commons_core -I ../../globals -I
../../h_program-lang *.mli *.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/lang_skip/parsing'
lang_skip/analyze
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/lang_skip/analyze'
ocamldep  -I ../../commons -I ../../globals -I ../../h_program-lang -I
../parsing *.mli *.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/lang_skip/analyze'
lang_nw/parsing
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/lang_nw/parsing'
ocamldep  -I ../../commons -I ../../globals -I ../../h_program-lang *.mli
*.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/lang_nw/parsing'
lang_nw/analyze
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/lang_nw/analyze'
ocamldep  -I ../../commons -I ../../commons_ocollection -I
../../h_program-lang -I ../../globals -I ../parsing *.mli *.ml > .depend
set -e; for i in ; do make -C $i depend; done
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/lang_nw/analyze'
lang_lisp/parsing
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/lang_lisp/parsing'
ocamldep  -I ../../commons -I ../../globals -I ../../h_program-lang *.mli
*.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/lang_lisp/parsing'
lang_lisp/analyze
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/lang_lisp/analyze'
ocamldep  -I ../../commons -I ../../commons_ocollection -I
../../commons_core -I ../../h_program-lang -I ../../graph_code -I
../../globals -I ../parsing *.mli *.ml > .depend
set -e; for i in ; do make -C $i depend; done
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/lang_lisp/analyze'
lang_haskell/parsing
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/lang_haskell/parsing'
ocamldep  -I ../../commons -I ../../globals -I ../../h_program-lang *.mli
*.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/lang_haskell/parsing'
lang_haskell/analyze
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/lang_haskell/analyze'
ocamldep  -I ../../commons -I ../../commons_ocollection -I
../../h_program-lang -I ../../globals -I ../parsing *.mli *.ml > .depend
set -e; for i in ; do make -C $i depend; done
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/lang_haskell/analyze'
lang_php/parsing
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/lang_php/parsing'
ocamldep  -I ../../commons -I ../../commons_core -I ../../globals -I
../../h_program-lang *.mli *.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/lang_php/parsing'
lang_php/pretty
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/lang_php/pretty'
ocamldep  -I ../../commons -I ../../globals -I ../../h_program-lang -I
../../lang_php/parsing *.mli *.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/lang_php/pretty'
lang_sql/parsing
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/lang_sql/parsing'
ocamldep  -I ../../commons -I ../../h_program-lang *.mli *.ml > .depend
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/lang_sql/parsing'
lang_js/parsing
make[1]: Entering directory
'/home/gabriele/Documents/workspace/git/pfff/lang_js/parsing'
menhir --unused-tokens --explain --fixed-exception parser_js.mly
File "parser_js.mly", line 130, characters 10-11:
Error: unexpected character(s).
Makefile:62: recipe for target 'parser_js.ml' failed
make[1]: *** [parser_js.ml] Error 1
make[1]: Leaving directory
'/home/gabriele/Documents/workspace/git/pfff/lang_js/parsing'
Makefile:277: recipe for target 'depend' failed
make: *** [depend] Error 2

STDERR is just this part:

main_codequery.ml:83:208: warning: missing terminating ' character
 no -Dpa.filternull=yes -Dpa.unknowntypes=no net.sf.bddbddb.Solver %s' %
(java_cmd, cla
                                                                     ^
main_codequery.ml:143:9: warning: missing terminating ' character
   (* don't care about the remaining prolog stuff so exit earlier *)
         ^
cc1: warning: unrecognized command line option ‘-Wno-invalid-pp-token’
main_codeslicer.ml:19:12: warning: missing terminating ' character
  * Once you've seen one driver you got the main ideas and seeing
            ^
main_codeslicer.ml:23:22: warning: missing terminating ' character
  * architecture as it's difficult to find a meaningful layering of the code
                      ^
main_codeslicer.ml:41:21: warning: missing terminating ' character
  * is far smaller it's also faster to run expensive analysis that are
                     ^
main_codeslicer.ml:143:43: warning: missing terminating ' character
      * but that should not anymore, so let's reconsider all children!
                                           ^
cc1: warning: unrecognized command line option ‘-Wno-invalid-pp-token’
File "parser_js.mly", line 130, characters 10-11:
Error: unexpected character(s).
make[1]: *** [parser_js.ml] Error 1
make: *** [depend] Error 2

I should clarify that I am on Ubuntu Desktop 18.04, with Opam 2.0.4 and
Ocaml 4.05.0. Also I have already successfully installed pfff through
ocaml, so all the ocaml dependecies should be met.

Gabriele

**Comment by GabrieleMaurina** [comment]
Hi Yoann,
I'm sorry to bother you again. Did you have a chance to take a look at the
error message I sent you? It seems to be complaining about the code itself (
parser_js.ml).

I would really love to get pfff working on my machine. Because of all the
other tools available online, that do similar things, pfff seems to be best
one for what I need to do.

Sincerely,
Gabriele
