### ISSUE TITLE
Consider to switch to ELPI for the Prolog queries

### ISSUE THREAD

**Issue by XVilka** [returntocorp/pfff#64]
So there will be less external dependencies - no need for SWI Prolog anymore.

[ELPI](https://github.com/LPCIC/elpi) - Embeddable λProlog Interpreter.

You can see their [API documentation](https://lpcic.github.io/elpi/elpi/Elpi/index.html) and the example of more complex program using it - [coq-elpi](https://github.com/LPCIC/coq-elpi)

**Comment by aryx** [comment]
I doubt it's as fast as SWI prolog.
