### ISSUE TITLE
Migrate off camlp4

### ISSUE THREAD

**Issue by XVilka** [returntocorp/pfff#65]
Camlp4 release for OCaml 4.08 is the last release ever - see the [official announcement](https://discuss.ocaml.org/t/the-end-of-camlp4/4216). It is recommended to port the code to use ppx (extension points), or any external parser (like mehrir, sedlex, ocamllex, ansgtrom, etc).

http://opam.ocaml.org/packages/pfff/ shows there is a dependency on camlp4, thus this issue.

But pfff can't be installed with 4.09 and 4.10 OCaml releases. Please consider to get rid of that dependency.

**Comment by aryx** [comment]
done
